# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  - trigger: :date
    replace: "{{date}}"
    vars:
      - name: date
        type: date
        params:
          format: "%Y-%m-%d"

  - triggers: [":daily-log", ":dl"]
    replace: |
      ---
      title: "{{date}}"
      ---

      Tags: [[Daily Log]]

      <br />

    vars:
      - name: date
        type: date
        params:
          format: "%B%e, %Y"

  - triggers: [":email", ":hi@"]
    replace: "hi@alexdunne.net"

  - trigger: :sig
    replace: |
      Kind regards,
      Alex
